application: toycpu
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
#- url: /.*
#  script: handlers.app

# Main page handler
- url: /
  static_files: static/index.html
  upload: static/index.html

# CSS handler
- url: /(.*\.css)
  static_files: static/\1
  upload: static/(.*\.css)

# JavaScript files
- url: /(.*\.js)
  static_files: static/\1
  upload: static/(.*\.js)

